Update error message for 107304
fl0co/RC24-Bot pull request #93
Opened 2019-11-15 19:09 UTC by urmum-69

2019-11-15 19:18 UTC, Artuto requested changes
Changes

2019-11-15 19:18 UTC, Artuto commented on src/main/java/xyz/rc24/bot/commands/wii/ErrorInfoCmd.java
> +        put(107304, "This error is can be caused by your isp blocking custom DNS servers, or simply not having it entered. Make sure it is entered correctly, if you still get this error use https://g
`is can be`

Capitalize ISP.

2019-11-15 19:22 UTC, urmum-69 commented on src/main/java/xyz/rc24/bot/commands/wii/ErrorInfoCmd.java
> +        put(107304, "This error is can be caused by your isp blocking custom DNS servers, or simply not having it entered. Make sure it is entered correctly, if you still get this error use https://g
oops, I not sure how I missed that one

2019-11-16 01:45 UTC, Artuto approved these changes

2019-11-16 01:45 UTC, merged